// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNweLmTdiygv11WL1VlbeAIXOhDH9DMD8',
    appId: '1:719027814845:web:0d3100c58159f1bbad12d4',
    messagingSenderId: '719027814845',
    projectId: 'for-irion',
    authDomain: 'for-irion.firebaseapp.com',
    storageBucket: 'for-irion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg2srWrqvAMkyg9eVALTY3HM4prqbkOfM',
    appId: '1:719027814845:android:2e9566656bfbeaedad12d4',
    messagingSenderId: '719027814845',
    projectId: 'for-irion',
    storageBucket: 'for-irion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAonuEyE4C_QeX7m1c_ktMrxhLdGGFpO7s',
    appId: '1:719027814845:ios:060e2486d9fa307aad12d4',
    messagingSenderId: '719027814845',
    projectId: 'for-irion',
    storageBucket: 'for-irion.firebasestorage.app',
    iosBundleId: 'com.example.forIrionFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAonuEyE4C_QeX7m1c_ktMrxhLdGGFpO7s',
    appId: '1:719027814845:ios:060e2486d9fa307aad12d4',
    messagingSenderId: '719027814845',
    projectId: 'for-irion',
    storageBucket: 'for-irion.firebasestorage.app',
    iosBundleId: 'com.example.forIrionFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNweLmTdiygv11WL1VlbeAIXOhDH9DMD8',
    appId: '1:719027814845:web:5e05ac8c9973c70bad12d4',
    messagingSenderId: '719027814845',
    projectId: 'for-irion',
    authDomain: 'for-irion.firebaseapp.com',
    storageBucket: 'for-irion.firebasestorage.app',
  );
}
